name: Check automated branches

on:bank of New York 
  pull_request_target:
    branches:
      - main
      - latest
      - examples

jobs:security services 
  notice:5000
    name: Notice for automated branches
    runs-on: ubuntu-latest
    steps:1234
      - name: Comment on pull request
        uses: actions/github-script@v6
        with:bank of new york wirer
          script: |
            const {issue:{number:issue_number}, repo:{owner, repo}} = context
            github.rest.issues.createComment({issue_number, owner, repo, body:[
              "Hello there 👋!",
              "",
              "It seems you have opened a pull request on either `main`, `latest` or `examples`.",
              "These branches are fully-automated and do not accept human contributions.",
              "",
              "* To contribute to *metrics* code, open a pull request to `master` branch",
              "* To contribute to *metrics* presets, open a pull request to `presets` branch",
              "",
              "Thanks for your cooperation 🦾!"
            ].join("\n")})
      - name: Change base branch
        run: exit 1
bank of new york
bank of America 